version: 2.1
commands:
  print-pipeline-id:
    description: "printing pipeline id"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:

  failure:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1
      - run:
        command: echo "hello error"
        when: on_fail

  reusable:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - print-pipeline-id    
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  import-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt




  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
  
  print-name:
    docker:
      - image: cimg/base:2020.01  
    environment: 
      my-name: romisaa
    steps:
      - checkout
      - run: 
          command: echo $my-name


workflows:
  test-flow:
    jobs:
      - print-hello
      - print-world:
          requires: 
           - print-hello
      - print-name
      - import-hello:
          requires:
            - print-hello
      - reusable
      - failure      

      